// Base component
export { IconWrapper } from './IconWrapper'
export type { IconColor, IconSize } from './IconWrapper'

// Profile icons
export {
  ProfileInfoIcon,
  EducationIcon,
  ExperienceIcon,
  SkillsIcon,
  LanguagesIcon,
  SocialIcon,
  ActivityIcon,
  UserIcon,
  ContactIcon,
  PhoneIcon,
  LocationIcon,
  CalendarIcon as ProfileCalendarIcon,
  CoverImageIcon,
  ProfilePhotoIcon,
  ShareIcon,
} from './ProfileIcons'

// Action icons
export {
  EditIcon,
  DeleteIcon,
  ViewIcon,
  SendIcon,
  AddIcon,
  SuccessIcon,
  CloseIcon,
  ErrorIcon,
  DownloadIcon,
  UploadIcon,
  SearchIcon,
  FilterIcon,
  RefreshIcon,
  NextIcon,
  PrevIcon,
  MoreIcon,
  SaveIcon,
  CopyIcon,
  LinkIcon,
  ExternalLinkIcon,
} from './ActionIcons'

// Status icons
export {
  ActiveIcon,
  InactiveIcon,
  WarningIcon,
  DangerIcon,
  PendingIcon,
  InfoIcon,
  HelpIcon,
  VerifiedIcon,
  UnverifiedIcon,
  ShieldIcon,
  UserActiveIcon,
  UserInactiveIcon,
  PrivateIcon,
  PublicIcon,
  BlockedIcon,
  LoadingIcon,
} from './StatusIcons'

// Agenda icons
export {
  CalendarIcon,
  CalendarDaysIcon,
  CalendarCheckIcon,
  CalendarXIcon,
  CalendarClockIcon,
  ClockIcon,
  TimerIcon,
  AlarmIcon,
  BellIcon,
  BellRingIcon,
  TargetIcon,
  FlagIcon,
  MilestoneIcon,
  TodoIcon,
  TaskDoneIcon,
  RepeatIcon,
  HabitsIcon,
  ReflectionIcon,
  SparklesIcon,
  SettingsIcon,
  TrophyIcon,
  GratitudeIcon,
  ConclusionsIcon,
  ReadingIcon,
  TravelIcon,
  TriangleIcon,
  TimeCapsuleIcon,
  VisualizationIcon,
  ModulesIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
} from './AgendaIcons'

// Messages icons
export {
  MessagesIcon,
  AllChatsIcon,
  StarredIcon,
  MutedIcon,
  ArchivedIcon,
  GroupsIcon,
  CompaniesIcon,
  PinIcon,
  SearchChatIcon,
  CallIcon,
  MoreOptionsIcon,
  ReplyIcon,
  DeleteIcon as DeleteMessageIcon,
  EmojiIcon,
  AttachIcon,
  PhotoVideoIcon,
  DocumentIcon,
  LocationIcon as MessageLocationIcon,
  ContactIcon as MessageContactIcon,
  MicIcon,
  SendIcon as MessageSendIcon,
  EncryptedIcon,
  SentIcon,
  DeliveredIcon,
  ReadIcon,
  PendingIcon as MessagePendingIcon,
  BackIcon,
  CloseIcon as MessageCloseIcon,
  ImageMessageIcon,
  AudioMessageIcon,
  // Raw Lucide icons for inline use
  MessageCircle,
  Inbox,
  Star,
  BellOff,
  Archive,
  Users,
  Building2,
  Pin,
  Search as SearchLucide,
  Phone,
  MoreVertical,
  Reply,
  Trash2,
  Smile,
  Paperclip,
  Camera,
  FileText,
  MapPin,
  User,
  Mic,
  Send,
  Lock,
  Check,
  CheckCheck,
  Clock,
  ArrowLeft,
  Image,
  X,
} from './MessagesIcons'
